apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-q8ee
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-q8ee
    app.kubernetes.io/part-of: ci1t-830-0024-app
  name: devfile-sample-q8ee
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-q8ee
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-q8ee
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/ci1t-830-0024-tenant/ci1t-830-0024-app/devfile-sample-q8ee@sha256:5ae69d0e06f4bd62a387a4f54c43fc014348adea5d7abe69f3f6250392ba93ee
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
